FROM python:3.9-bullseye
# RUN  pip install --upgrade pip \ pymongo \ pandas \ pyarrow \ mysql-connector-python

RUN mkdir -p /workspaces/app
RUN apt update 
RUN apt install nano

COPY /builder /workspaces/app/builder
COPY /requirements.txt /workspaces/app/requirements.txt
COPY /main.py /workspaces/app/main.py

WORKDIR /workspaces/app
RUN pip install -r requirements.txt
RUN pip install --no-cache-dir cryptography

ENV PYTHONPATH=/usr/local/lib/python3.9/dist-packages
ENV CONTAINERPATH=/workspaces/app

# CMD ["python","data_generator.py","sleep 20s","python fundamentus.py","sleep 20s","python mongo_etl.py"]