SELECT 

distinct
papel,
coalesce(DENOM_COMERC,'na') as DENOM_COMERC,
div_yield,
coalesce(atuacao,'na') as atuacao,
coalesce(segmento_listagem,'na') as segmento_listagem,
cresc_rec_cinco_anos,
coalesce(SUBSTRING_INDEX(reclameaquinota, ' / ', 1),-1) as reclameaquinota,
coalesce(reclameaquitexto,'na') as reclameaquitexto,
patrim_liq

FROM obt_b3 ob 
where atuacao = 'bancos'


SELECT 
cnpj, 
papel, 
cotacao, 
pl, 
pvp, 
psr, 
div_yield, 
p_ativo, 
p_cap_giro, 
p_ebit, 
p_ativ_circ_liq, 
ev_ebit, 
ev_ebitda, 
mrg_ebit, 
mrg_liq, 
liq_corr, 
roic, 
roe, 
liq_2meses, 
patrim_liq, 
div_bruta_patrim, 
cresc_rec_cinco_anos, 
CNPJ_CIA, 
DENOM_COMERC, 
DT_REG, 
SIT, 
AUDITOR, 
atuacao, 
segmento_listagem, 
tag_alongon, 
tag_alongpn, 
freefloaton, 
freefloatpn, 
on_percent, 
pn_percent, 
reclameaquinota, 
reclameaquitexto, 
DT_REFER, 
VERSAO, 
DENOM_CIA, 
CD_CVM, 
GRUPO_DFP, 
MOEDA, 
ESCALA_MOEDA, 
ORDEM_EXERC, 
DT_INI_EXERC, 
DT_FIM_EXERC, 
CD_CONTA, 
DS_CONTA, 
VL_CONTA, 
ST_CONTA_FIXA
FROM db.obt_b3;