-- Create the calendar table
CREATE TABLE calendar (
    ano INT,
    mes INT,
    dia INT,
    nome_do_dia VARCHAR(20)
);

-- Populate the calendar table with dates and day names
INSERT INTO calendar (ano, mes, dia, nome_do_dia)
SELECT 
    YEAR(date) AS ano,
    MONTH(date) AS mes,
    DAY(date) AS dia,
    DAYNAME(date) AS nome_do_dia
FROM (
    SELECT 
        ADDDATE('2023-01-01', INTERVAL (a.a + (10 * b.a) + (100 * c.a)) DAY) AS date
    FROM
        (SELECT 0 AS a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS a
    CROSS JOIN
        (SELECT 0 AS a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS b
    CROSS JOIN
        (SELECT 0 AS a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS c
    WHERE
        ADDDATE('2023-01-01', INTERVAL (a.a + (10 * b.a) + (100 * c.a)) DAY) BETWEEN '2023-01-01' AND '2024-12-31'
) AS dates;
