CREATE TABLE cad (
    CNPJ_CIA           TEXT,
    DENOM_SOCIAL       TEXT,
    DENOM_COMERC       TEXT,
    DT_REG             TEXT,
    DT_CONST           TEXT,
    DT_CANCEL          TEXT,
    MOTIVO_CANCEL      TEXT,
    SIT                TEXT,
    DT_INI_SIT         TEXT,
    CD_CVM             TEXT,
    SETOR_ATIV         TEXT,
    TP_MERC            TEXT,
    CATEG_REG          TEXT,
    DT_INI_CATEG       TEXT,
    SIT_EMISSOR        TEXT,
    DT_INI_SIT_EMISSOR TEXT,
    CONTROLE_ACIONARIO TEXT,
    TP_ENDER           TEXT,
    LOGRADOURO         TEXT,
    COMPL              TEXT,
    BAIRRO             TEXT,
    MUN                TEXT,
    UF                 TEXT,
    PAIS               TEXT,
    CEP                TEXT,
    DDD_TEL            TEXT,
    TEL                TEXT,
    DDD_FAX            TEXT,
    FAX                TEXT,
    EMAIL              TEXT,
    TP_RESP            TEXT,
    RESP               TEXT,
    DT_INI_RESP        TEXT,
    LOGRADOURO_RESP    TEXT,
    COMPL_RESP         TEXT,
    BAIRRO_RESP        TEXT,
    MUN_RESP           TEXT,
    UF_RESP            TEXT,
    PAIS_RESP          TEXT,
    CEP_RESP           TEXT,
    DDD_TEL_RESP       TEXT,
    TEL_RESP           TEXT,
    DDD_FAX_RESP       TEXT,
    FAX_RESP           TEXT,
    EMAIL_RESP         TEXT,
    CNPJ_AUDITOR       TEXT,
    AUDITOR            TEXT,
    data_carga         DATE,
    run_id             TEXT
) DEFAULT CHARSET=utf8 DEFAULT COLLATE=utf8_general_ci;


CREATE TABLE dfp_cia_aberta_DRE_con_2023 (
CNPJ_CIA  text,
DT_REFER  text,
VERSAO    bigint,
DENOM_CIA text,
CD_CVM    bigint,
GRUPO_DFP text,
MOEDA     text,
ESCALA_MOEDA  text,
ORDEM_EXERC   text,
DT_INI_EXERC  text,
DT_FIM_EXERC  text,
CD_CONTA  text,
DS_CONTA  text,
VL_CONTA  double,
ST_CONTA_FIXA text,
data_carga date,
run_id    text
) DEFAULT CHARSET= utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE fundamentus (
papel text,
cotacao double,
pl double,
pvp double,
psr double,
div_yield double,
p_ativo double,
p_cap_giro double,
p_ebit double,
p_ativ_circ_liq double,
ev_ebit double,
ev_ebitda double,
mrg_ebit double,
mrg_liq double,
liq_corr double,
roic double,
roe double,
liq_2meses double,
patrim_liq double,
div_bruta_patrim double,
cresc_rec_cinco_anos double,
data_carga date,
run_id text

) DEFAULT CHARSET=utf8 DEFAULT COLLATE=utf8_general_ci;


CREATE TABLE fundamentei (
cnpj              text,
tickeron          text,
tickerpn          text,
nome              text,
atuacao           text,
segmento_listagem text,
tag_alongon       text,
tag_alongpn       text,
freefloaton       text,
freefloatpn       text,
on_percent        text,
pn_percent        text,
socio             text,
reclameaquinota   text,
reclameaquitexto  text CHARSET=utf8,
reclameaquiatualizadoem text,
data_carga        date,
run_id            text
) DEFAULT CHARSET=utf8 DEFAULT COLLATE=utf8_general_ci;


ALTER DATABASE db CHARACTER SET = utf32 COLLATE = utf32_general_ci;