FROM python:3.9-bullseye

# RUN  pip install --upgrade pip \ pymongo \ pandas \ pyarrow \ mysql-connector-python

RUN mkdir -p /workspaces/app
RUN apt update 
RUN apt install nano

COPY /requirements.txt /workspaces/app/requirements.txt
COPY /environment.py /workspaces/app/environment.py
COPY /analytics.py /workspaces/app/analytics.py
COPY fundamentei.parquet /workspaces/app/fundamentei.parquet
COPY cad.parquet /workspaces/app/cad.parquet
COPY dfp_cia_aberta_DRE_con_2023.parquet /workspaces/app/dfp_cia_aberta_DRE_con_2023.parquet
COPY fundamentus.parquet /workspaces/app/fundamentus.parquet

WORKDIR /workspaces/app
RUN pip install -r requirements.txt
RUN pip install --no-cache-dir cryptography

ENV PYTHONPATH=/usr/local/lib/python3.9/dist-packages

# CMD ["python","data_generator.py","sleep 20s","python fundamentus.py","sleep 20s","python mongo_etl.py"]